version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api-server
    command: sh -c "npm run debug"
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - jenkins_estudo_app:/usr/app
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - jenkins_estudo
    environment:
      - TZ:"America/Sao_Paulo"

  db:
    image: postgres:14
    volumes:
      - jenkins_estudo:/var/lib/postgresql/data
    command: postgres -c 'max_connections=81'
    container_name: jenkins-estudo-db
    ports:
      - ${LOCAL_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - jenkins_estudo

networks:
  jenkins_estudo:
    driver: bridge

volumes:
  jenkins_estudo:
    driver: local

  jenkins_estudo_app:
    driver: local